name: Generate GitHub Breakout

on:
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Breakout
        uses: cyprieng/github-breakout@v1
        with:
          github_username: KishoreGowda17
          paddle_color: "#190126"
          ball_color: "#ffffff"
          bricks_colors: "#052E16,#166534,#15803D,#22C55E,#86EFAC"

      - name: Move custom SVG
        run: |
          mkdir -p /tmp/breakout-images
          mv output/custom.svg /tmp/breakout-images/breakout-custom.svg

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update breakout branch
        run: |
          git checkout --orphan github-breakout
          git rm -rf .
          mkdir images
          mv /tmp/breakout-images/breakout-custom.svg images/
          git add images
          git commit -m "chore: update GitHub breakout SVGs" || echo "No changes to commit"
          git push --force origin github-breakout
